2025-05-30 22:59:15,192 ERROR: Server Error: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:211]
Traceback (most recent call last):
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\Desktop\Lernio\app\student_routes.py", line 21, in decorated_function
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ENVY\Desktop\Lernio\app\student_routes.py", line 71, in dashboard
    cast(ActivityLog.timestamp, Date).label('date'),
         ^^^^^^^^^^^
NameError: name 'ActivityLog' is not defined
2025-05-30 23:13:06,642 INFO: Lernio startup [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:185]
2025-05-30 23:13:10,133 INFO: Lernio startup [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:185]
2025-05-30 23:13:14,911 INFO: Загрузка пользователя с ID: 4 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-30 23:13:14,912 INFO: Пользователь загружен из локальных данных: 123 (роль: student) [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:72]
2025-05-30 23:13:16,233 INFO: Загрузка пользователя с ID: 4 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-30 23:13:16,234 INFO: Пользователь найден в сессии: 4 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:50:00,056 INFO: Lernio startup [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:185]
2025-05-31 09:50:39,978 INFO: Пользователь Olima успешно вошел в систему [in C:\Users\ENVY\Desktop\Lernio\app\local_auth.py:147]
2025-05-31 09:50:40,019 INFO: [2025-05-31 09:50:40] User 1: login_success [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:50:40,173 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:50:40,261 INFO: Пользователь загружен из локальных данных: teacher (роль: teacher) [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:72]
2025-05-31 09:50:40,395 INFO: [2025-05-31 09:50:40] User 1: view_teacher_dashboard [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:00,545 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:00,545 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:00,554 INFO: [2025-05-31 09:51:00] User 1: logout [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:08,453 INFO: Пользователь Olima успешно вошел в систему [in C:\Users\ENVY\Desktop\Lernio\app\local_auth.py:147]
2025-05-31 09:51:08,460 INFO: [2025-05-31 09:51:08] User 1: login_success [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:08,468 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:08,469 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:08,477 INFO: [2025-05-31 09:51:08] User 1: view_teacher_dashboard [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:09,691 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:09,696 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:09,707 INFO: [2025-05-31 09:51:09] User 1: view_manage_students [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:11,440 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:11,441 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:28,865 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:28,865 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:47,377 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:47,377 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:47,671 INFO: [2025-05-31 09:51:47] User 1: add_student_8 - Username: 12345 [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:47,675 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:47,675 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:47,681 INFO: [2025-05-31 09:51:47] User 1: view_manage_students [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:53,164 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:53,165 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:51:53,170 INFO: [2025-05-31 09:51:53] User 1: logout [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:58,948 INFO: Пользователь 12345 успешно вошел в систему [in C:\Users\ENVY\Desktop\Lernio\app\local_auth.py:147]
2025-05-31 09:51:58,953 INFO: [2025-05-31 09:51:58] User 8: login_success [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:51:58,960 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:51:58,966 INFO: Пользователь загружен из базы данных: 12345 (роль: student) [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:97]
2025-05-31 09:51:59,264 INFO: [2025-05-31 09:51:59] User 8: view_student_dashboard [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:52:34,621 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:34,621 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:35,736 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:35,737 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:37,214 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:37,214 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:37,723 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:37,723 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:37,729 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:37,729 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:37,738 INFO: [2025-05-31 09:52:37] User 8: view_student_dashboard [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 09:52:38,575 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:38,575 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:49,311 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:49,312 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:49,316 INFO: Загрузка пользователя с ID: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 09:52:49,317 INFO: Пользователь найден в сессии: 8 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 09:52:49,323 INFO: [2025-05-31 09:52:49] User 8: view_student_dashboard [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 20:02:36,749 INFO: Lernio startup [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:185]
2025-05-31 20:03:11,343 INFO: Пользователь Olima успешно вошел в систему [in C:\Users\ENVY\Desktop\Lernio\app\local_auth.py:147]
2025-05-31 20:03:11,361 INFO: [2025-05-31 20:03:11] User 1: login_success [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 20:03:11,383 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 20:03:11,388 INFO: Пользователь загружен из локальных данных: teacher (роль: teacher) [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:72]
2025-05-31 20:03:11,436 INFO: [2025-05-31 20:03:11] User 1: view_teacher_dashboard [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
2025-05-31 20:04:07,537 INFO: Загрузка пользователя с ID: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:61]
2025-05-31 20:04:07,540 INFO: Пользователь найден в сессии: 1 [in C:\Users\ENVY\Desktop\Lernio\app\__init__.py:65]
2025-05-31 20:04:07,603 INFO: [2025-05-31 20:04:07] User 1: view_teacher_dashboard [in C:\Users\ENVY\Desktop\Lernio\app\utils\__init__.py:35]
